---
title: Stone The Crows
timezone: UTC
collections:
  postcards:
    title: Postcards
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: "@CorCorvus"
github_username: Pixy5
sass:
  sass_dir: _sass
markdown: kramdown
google_analytics: UA-143380934-1
google_tagmanager: GTM-KZBHCZ4

